name: PlatformIO compile

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Python setup
      uses: actions/setup-python@v1
      
    - name: PlatformIO setup
      run: |
        python -m pip install --upgrade pip
        pip install platformio
    - name: PIO compile
      run: platformio run -e nodemcuv2
